function stats = vgsGetLastSectionStats ( )
% S=VGSGETLASTSECTIONSTATS() returns last section statistics.
%
% (c) 2010 ÚTIA AVÈR, v.v.i.
%
% Author: Jan Pøikryl <prikryl@utia.cas.cz>
%
% Version: $Id: vgsSetup.m 2357 2009-05-04 11:46:17Z prikryl $
%

    tstats = struct ( ...
        'flow', 0, ...
        'travelTimeAvg', 0, ...
        'travelTimeSdv', 0, ...
        'delayTimeAvg', 0, ...
        'delayTimeSdv', 0, ...
        'speedAvg', 0, ...
        'speedSdv', 0, ...
        'density', 0, ...
        'stopTimeAvg', 0, ...
        'stopTimeSdv', 0, ...
        'numStops', 0, ...
        'queueAvg', 0, ...
        'queueMax', 0 ...
        );

    stats = struct();
    stats.time = 0;
    stats.stats = repmat ( tstats, [1 200] );
    stats.queues = zeros ( 1, 800 );
    stats.length = 0;
    stats.max_lanes = 0;

    % Obtain the last section statistics written in the buffer
    [ r, stats ] = calllib ( 'vgs_api', 'vgs_get_last_stats', stats );
    
% ----- END ( vgsGetLastSectionStats ) -----